name: Dependencies Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 2'

jobs:
  update_dependencies_annotation:
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        uses: peiffer-innovations/actions-dart-dependency-updater@v1
        with:
          merge: true
          paths: packages/annotation
          pull_request: true
          token: ${{ secrets.REPO_TOKEN }}

  update_dependencies_codegen:
    needs:
      - update_dependencies_annotation
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        uses: peiffer-innovations/actions-dart-dependency-updater@v1
        with:
          merge: true
          paths: packages/codegen
          pull_request: true
          token: ${{ secrets.REPO_TOKEN }}

  update_dependencies:
    needs:
      - update_dependencies_codegen
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        uses: peiffer-innovations/actions-dart-dependency-updater@v1
        with:
          merge: true
          paths: packages/json_theme,json_theme/example
          pull_request: true
          token: ${{ secrets.REPO_TOKEN }}
